# Generated by Django 5.2.17 on 2026-09-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('card_type', models.CharField(choices=[('CREDIT', 'Credit Card'), ('DEBIT', 'Debit Card')], max_length=10)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('masked_card_number', models.CharField(max_length=20)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('expiry_month', models.IntegerField()),
                ('expiry_year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
